### ISSUE TITLE
Need LICENSE file in repo

### ISSUE THREAD

**Issue by btfranklin** [ArchieGoodwin/PineconeSwift#3]
Please add a license to this repo. Here's an explanation from SwiftPackageIndex.com about why this is important:

If the package license is showing as "No License" with a red exclamation icon, we could not find any license information in the package repository.

Using a package that does not have a license presents a significant legal risk. Unlicensed code is not open-source, and the original author reserves all rights by default. For more information, read [this great blog post](https://expressionengine.com/blog/the-truth-about-the-risks-of-unlicensed-software) on using unlicensed code.

If you are the package author, you can fix this by adding a LICENSE file with an open-source license in your package's repository. The Swift Package Index will update license metadata a few hours after you add the license.

**Comment by ArchieGoodwin** [comment]
Thank you for reminding, added
